# Catagorize and grade indivdual strokes against the references

In [1]:
import numpy as np

import load_strokes as load

In [2]:
X, y = load.loadXy("HanBitmap", "5E7E")

strokes = X[0]

In [8]:
stroke = strokes[0]
ref_stroke = strokes[1] # using a fake reference stroke for testing

y_true, x_true = np.where(stroke == 1)
coords = np.dstack((y_true, x_true))[0]
y_ref, x_ref = np.where(ref_stroke == 1)
ref_coords = np.dstack((y_ref, x_ref))[0]
min_dists = np.array([min([np.linalg.norm(c-r) for r in ref_coords]) for c in coords])
mse = np.sqrt(np.mean(np.square(min_dists)))

coords, ref_coords, min_dists, mse

(array([[4, 3],
        [5, 2],
        [6, 3],
        [7, 4],
        [8, 5]]),
 array([[ 9,  4],
        [10,  5],
        [11,  6],
        [12,  5],
        [12,  6],
        [12, 10],
        [13,  3],
        [13,  4],
        [13,  5],
        [13,  7],
        [13,  9],
        [14,  3],
        [14,  4],
        [14,  8],
        [15,  3],
        [16,  2]]),
 array([5.09901951, 4.47213595, 3.16227766, 2.        , 1.41421356]),
 3.521363372331802)

In [13]:
def strokeMeanSquaredError(stroke, ref):
    y_true, x_true = np.where(stroke == 1)
    coords = np.dstack((y_true, x_true))[0]
    y_ref, x_ref = np.where(ref_stroke == 1)
    ref_coords = np.dstack((y_ref, x_ref))[0]
    min_dists = np.array([min([np.linalg.norm(c-r) for r in ref_coords]) for c in coords])
    mse = np.sqrt(np.mean(np.square(min_dists)))
    return mse

def strokeMaxDevError(stroke, ref):
    y_true, x_true = np.where(stroke == 1)
    coords = np.dstack((y_true, x_true))[0]
    y_ref, x_ref = np.where(ref_stroke == 1)
    ref_coords = np.dstack((y_ref, x_ref))[0]
    max_dist = np.array([min([np.linalg.norm(c-r) for r in ref_coords]) for c in coords]).max()
    return max_dist
    
def strokeMeanAbsError(stroke, ref):
    y_true, x_true = np.where(stroke == 1)
    coords = np.dstack((y_true, x_true))[0]
    y_ref, x_ref = np.where(ref_stroke == 1)
    ref_coords = np.dstack((y_ref, x_ref))[0]
    min_dists = np.array([min([np.linalg.norm(c-r) for r in ref_coords]) for c in coords])
    abs_error = np.mean(np.abs(min_dists))
    return abs_error


In [14]:
strokeMeanAbsError(stroke, ref_stroke)

3.229529338226768